// Mocks generated by Mockito 5.3.2 from annotations
// in the_meal_flutter/src/core/client/api/base_api_client.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:mockito/mockito.dart' as _i1;
import 'package:the_meal_flutter/src/src.dart' as _i2;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

/// A class which mocks [BaseApiClient].
///
/// See the documentation for Mockito's code generation for more information.
class MockBaseApiClient extends _i1.Mock implements _i2.BaseApiClient {
  @override
  _i3.Future<dynamic> get(
    String? url, {
    String? token,
    dynamic responseType,
    Map<String, dynamic>? queryParams,
    Map<String, dynamic>? headers,
    int? msTimeout = 10000,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #get,
          [url],
          {
            #token: token,
            #responseType: responseType,
            #queryParams: queryParams,
            #headers: headers,
            #msTimeout: msTimeout,
          },
        ),
        returnValue: _i3.Future<dynamic>.value(),
        returnValueForMissingStub: _i3.Future<dynamic>.value(),
      ) as _i3.Future<dynamic>);
  @override
  _i3.Future<dynamic> patch(
    String? url, {
    dynamic data,
    String? token,
    Map<String, dynamic>? headers,
    Map<String, dynamic>? queryParams,
    String? contentType = r'application/json',
    int? msTimeout = 10000,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #patch,
          [url],
          {
            #data: data,
            #token: token,
            #headers: headers,
            #queryParams: queryParams,
            #contentType: contentType,
            #msTimeout: msTimeout,
          },
        ),
        returnValue: _i3.Future<dynamic>.value(),
        returnValueForMissingStub: _i3.Future<dynamic>.value(),
      ) as _i3.Future<dynamic>);
  @override
  _i3.Future<dynamic> post(
    String? url, {
    dynamic data,
    String? token,
    Map<String, dynamic>? headers,
    Map<String, dynamic>? queryParams,
    String? contentType = r'application/json',
    int? msTimeout = 10000,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #post,
          [url],
          {
            #data: data,
            #token: token,
            #headers: headers,
            #queryParams: queryParams,
            #contentType: contentType,
            #msTimeout: msTimeout,
          },
        ),
        returnValue: _i3.Future<dynamic>.value(),
        returnValueForMissingStub: _i3.Future<dynamic>.value(),
      ) as _i3.Future<dynamic>);
  @override
  _i3.Future<dynamic> delete(
    String? url, {
    dynamic data,
    String? token,
    Map<String, dynamic>? headers,
    Map<String, dynamic>? queryParams,
    String? contentType = r'application/json',
    int? msTimeout = 10000,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #delete,
          [url],
          {
            #data: data,
            #token: token,
            #headers: headers,
            #queryParams: queryParams,
            #contentType: contentType,
            #msTimeout: msTimeout,
          },
        ),
        returnValue: _i3.Future<dynamic>.value(),
        returnValueForMissingStub: _i3.Future<dynamic>.value(),
      ) as _i3.Future<dynamic>);
  @override
  _i3.Future<dynamic> put(
    String? url, {
    dynamic data,
    String? token,
    Map<String, dynamic>? headers,
    Map<String, dynamic>? queryParams,
    String? contentType = r'application/json',
    int? msTimeout = 10000,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #put,
          [url],
          {
            #data: data,
            #token: token,
            #headers: headers,
            #queryParams: queryParams,
            #contentType: contentType,
            #msTimeout: msTimeout,
          },
        ),
        returnValue: _i3.Future<dynamic>.value(),
        returnValueForMissingStub: _i3.Future<dynamic>.value(),
      ) as _i3.Future<dynamic>);
}
